[tool.poetry]
name = "aws-mfa"
version = "0.1.0"
description = "CLI tool to manage MFA credentials for AWS API access"
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "aws_mfa"}]

[tool.poetry.dependencies]
python = "^3.9"
boto3 = "^1.26.35"
click = "^8.1.3"

[tool.poetry.group.dev.dependencies]
black = "^22.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
