name: Lint & Test

on: push

jobs:
  lint_and_test:
    name: Lint & Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: '.'
    steps:
      - uses: actions/checkout@v3
      
      - name: Python Version
        id: python_version
        run: echo "version=$(cat .python-version)" >> $GITHUB_OUTPUT

      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install poetry
        run: pipx install poetry==1.2.1

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ steps.python_version.outputs.version }}
          cache: "poetry"

      - name: Install (dev) dependencies
        run: |
          poetry env use ${{ steps.python_version.outputs.version }}
          poetry install --with dev
        
      - name: Lint
        run: poetry run inv lint
      
      - name: Typecheck
        run: poetry run inv typecheck

      - name: Run Tests
        run: poetry run inv test

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: "./tests/*.xml"
          comment_mode: "always"

       